import { Platform } from 'react-native';

export const Colors = {
  light: {
    text: '#1a1a18',
    textMuted: '#6b6b67',
    background: '#ffffff',
    backgroundSecondary: '#f5f4f0',
    backgroundCanvas: '#EAF3DE',
    border: 'rgba(0,0,0,0.1)',
    tint: '#1D9E75',
    tabIconDefault: '#687076',
    tabIconSelected: '#1D9E75',
    green: '#1D9E75',
    greenLight: '#E1F5EE',
    greenDark: '#0F6E56',
    headerBg: '#EAF3DE',
    cardBg: '#f5f4f0',
    strip: '#FAEEDA',
  },
  dark: {
    text: '#ECEDEE',
    textMuted: '#9BA1A6',
    background: '#151718',
    backgroundSecondary: '#1e2022',
    backgroundCanvas: '#1a2e1f',
    border: 'rgba(255,255,255,0.1)',
    tint: '#1D9E75',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: '#1D9E75',
    green: '#1D9E75',
    greenLight: '#0d2e22',
    greenDark: '#9FE1CB',
    headerBg: '#1a2e1f',
    cardBg: '#1e2022',
    strip: '#2e2310',
  },
  forest: {
    text: '#1a2e1a',
    textMuted: '#4a6741',
    background: '#f0f7ee',
    backgroundSecondary: '#dff0d8',
    backgroundCanvas: '#c8e6c9',
    border: 'rgba(0,80,0,0.15)',
    tint: '#2e7d32',
    tabIconDefault: '#4a6741',
    tabIconSelected: '#2e7d32',
    green: '#2e7d32',
    greenLight: '#c8e6c9',
    greenDark: '#1b5e20',
    headerBg: '#c8e6c9',
    cardBg: '#dff0d8',
    strip: '#fff9c4',
  },
  sunset: {
    text: '#2d1b00',
    textMuted: '#7a4f2a',
    background: '#fff8f0',
    backgroundSecondary: '#fde8cc',
    backgroundCanvas: '#ffd5a0',
    border: 'rgba(120,60,0,0.15)',
    tint: '#e65100',
    tabIconDefault: '#7a4f2a',
    tabIconSelected: '#e65100',
    green: '#e65100',
    greenLight: '#fde8cc',
    greenDark: '#bf360c',
    headerBg: '#ffd5a0',
    cardBg: '#fde8cc',
    strip: '#e8f5e9',
  },
};

export type ThemeName = keyof typeof Colors;

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});